name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.environment}}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build

      - name: Deploy
        uses:  reggionick/s3-deploy@v3
        with:
          folder: packages/container/dist
          bucket:  ${{ vars.AWS_S3_BUCKET_NAME }}
          bucket-region: ${{ vars.AWS_DEFAULT_REGION }}
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: ".*/*,*/*,**"
            
