name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.environment}}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: bitovi/github-actions-deploy-static-site-to-aws@v0.2.2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: ${{ vars.AWS_DEFAULT_REGION }}
          aws_resource_identifier: ${{ vars.AWS_S3_BUCKET_NAME }}
          aws_site_bucket_name: ${{ vars.AWS_S3_BUCKET_NAME }}
          checkout: false
          aws_site_source_folder: packages/container/dist
          tf_action: 'apply'
          tf_state_bucket_destroy: true
          
